/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-03-29 09:41:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.dbutil.*;
import com.can.*;

public final class composeMail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/jsp/errorPage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("span{color:white;}\r\n");
      out.write("</style>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-image: url('/e-canvass/images/10.jpg');background-position:center; background-repeat: no-repeat;height:100%;width:100%;background-attachment: fixed;\">\r\n");
      out.write("<h2 style=\"text-align: center;text-decoration: underline;color:white;\">Compose Message...\r\n");
      out.write("</h2>\r\n");
HttpSession hs=request.getSession(false);
String userid=(String)hs.getAttribute("loginid");
String ty=(String)hs.getAttribute("type1");
/* String page1=(String)hs.getAttribute("page");
hs.setAttribute("page", page1);
 */
String s=request.getQueryString();
System.out.println("ye hai"+s);
String rec=(String)hs.getAttribute("rec");
System.out.println("sender id is "+userid);
hs.setAttribute("senderid", userid);
System.out.println(ty);
//logged in user id

      out.write("\r\n");
      out.write("<form action=\"/e-canvass/Mail?");
      out.print(ty );
      out.write("\" method=\"Post\">\r\n");
      out.write("<table style=\"position: absolute;left: 15%;\">\r\n");
      out.write("<tr><td style=\"display:none;\"><input type=\"text\" name=\"senderid\"></td></tr>\r\n");
      out.write("<tr><td >\r\n");
      out.write("<span>To:</span></td><td><input type=\"text\" name=\"id\" value=");
      out.print(s);
      out.write("></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td >\r\n");
      out.write("<span>Subject:</span></td><td><input type=\"text\" value=\"\" name=\"subject\">\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td >\r\n");
      out.write("<span>Message:</span></td><td><textarea name=\"message\" rows=\"20\" cols=\"100\"></textarea>\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td></td><td>\r\n");
      out.write("<input type=\"submit\" value=\"send\">\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
