/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-03-29 13:50:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.dbutil.*;
import com.can.*;

public final class inbox_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/e-canvass/jsp/errorPage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap-responsive.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap-responsive.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap.js\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap.min.js\">\r\n");
      out.write("<title>Inbox...</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-image: url('/e-canvass/images/6.jpg');background-position:center; background-repeat: no-repeat;height:100%;width:100%;background-attachment: fixed;\">\r\n");
HttpSession hs=request.getSession(false);
String s=request.getQueryString();
hs.setAttribute("whichbox","inbox");

      out.write("\r\n");
      out.write("<a href=\"/e-canvass/jsp/");
      out.print(s );
      out.write(".jsp\" style=\"float:left;color:white;\">Back....</a>\r\n");
      out.write("<h3 style=\"text-align: center;text-decoration: underline;color:white\">Inbox....</h3>\r\n");
      out.write("<form action=\"/e-canvass/DeleteRec?");
      out.print(s );
      out.write("\" method=\"Post\">\r\n");
      out.write("<table border=\"1\" style=\"left:100px;width: 80%;background-color: white;position: relative;border-color: brown;\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th>Select</th>\r\n");
      out.write("<th>From</th>\r\n");
      out.write("<th>Subject</th>\r\n");
      out.write("<th>Message</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");

String userid=(String)hs.getAttribute("loginid");
hs.setAttribute("whoItIs",s);
Connection con=null;PreparedStatement ps=null;ResultSet rs=null;
String strsql="select * from messages where receiverid=?";
int k=50;
con=CRUDOperation.createConection();
	try
	{   hs=request.getSession();
		ps=con.prepareStatement(strsql);
		ps.setString(1, userid);
		rs=ps.executeQuery();
		while(rs.next())
		{   if(rs.getString("rstatus").equals("true"))
		{
			System.out.println("1");
			if((rs.getString("messagetext")).length()<=50)
				k=(rs.getString("messagetext")).length();
		
      out.write("\r\n");
      out.write("<tr><td style=\"text-align: center;\"><input type=\"checkbox\" value=\"");
      out.print(rs.getString("messageid") );
      out.write("\" name=\"chkbx\" ></td>\r\n");
      out.write("<td style=\"text-align: center;\">");
      out.print(rs.getString("senderid") );
      out.write("</td> \r\n");
      out.write("<td style=\"text-align: center;\">");
      out.print(rs.getString("subject") );
      out.write("</td>\r\n");
      out.write("<td style=\"text-align: center;\"><a href=\"/e-canvass/jsp/viewmessage.jsp?");
      out.print(rs.getString("messageid") );
      out.write('"');
      out.write('>');
      out.print((rs.getString("messagetext")).substring(0, k) );
      out.write("</a></td>\r\n");
}
			}
		}
	catch(SQLException se)
	{
	System.out.println(se);}
	

      out.write("\r\n");
      out.write("<tr><td colspan=\"4\"><input type=\"submit\" value=\"Delete\"></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
