/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-03-29 09:36:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/e-canvass/jsp/errorPage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap-responsive.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap-responsive.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap.js\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap.min.js\">\r\n");
      out.write("<title>Registration..</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function checkuserid(uid)\r\n");
      out.write("{\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tif(XMLHttpRequest)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tx=new XMLHttpRequest();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tx.onreadystatechange=function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(x.readyState==4 && x.status==200)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tvar info=x.responseText;//used to store the response send by the server\r\n");
      out.write("\t\tdocument.getElementById(\"msgtxt\").innerHTML=info;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tx.open(\"GET\",\"/e-canvass/register?us=\"+uid,true);\r\n");
      out.write("\tx.send(null);\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-image: url('/e-canvass/images/1.jpg\t');background-size: 100% 650px;\">\r\n");
      out.write("<div>\r\n");
      out.write("<h2 style=\"text-align: center;\">REGISTER...</h2>\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"/e-canvass/registration\" method=\"post\">\r\n");
      out.write("<table  style=\"top:10%;left:34%;height:500px;width:500px;position:absolute;\">\r\n");
      out.write("<tr style=\"color:blue;\"><td >Name </td><td colspan=\"2\"><input type=\"text\" name=\"name\"/></td></tr>\r\n");
      out.write("<tr style=\"color:blue;\"><td >AdmissionNo. </td><td colspan=\"2\"><input type=\"text\" name=\"admissionno\" onblur=\"checkuserid(this.value)\" />\r\n");
      out.write("<p id=\"msgtxt\" style=\"color:red;\"></p></td></tr>\r\n");
      out.write("<tr style=\"color:blue;\"><td >University RollNo. </td><td colspan=\"2\"><input type=\"text\" name=\"universityroll\" onblur=\"checkuserid(this.value)\" />\r\n");
      out.write("<tr style=\"color:blue;\"><td>Password</td>\r\n");
      out.write("<td colspan=\"2\"><input type=\"password\" name=\"password\"/></td></tr>\r\n");
      out.write("<tr style=\"color:blue;\"><td>PhoneNumber</td><td colspan=\"2\"><input type=\"text\" name=\"phonenumber\"/></td></tr>\r\n");
      out.write("<tr style=\"color:blue;\"><td>Type</td><td>Teacher<input type=\"radio\" name=\"type\" value=\"teacher\" onclick=\"hideFacility()\"></td><td>Student<input type=\"radio\" name=\"type\" value=\"student\" onclick=\"showFacility()\"></td></tr>\r\n");
      out.write("<tr style=\"color:blue; \"><td>Department</td>\r\n");
      out.write("<td colspan=\"2\"><select name=\"department\" >\r\n");
      out.write("<option value=\"IT\">Information Technology</option>\r\n");
      out.write("<option value=\"CS\">Computer Science</option>\r\n");
      out.write("<option value=\"ME\">Mechanical Engineering</option>\r\n");
      out.write("<option value=\"EE\">Electrical Engineering</option></select></td></tr>\r\n");
      out.write("<tr><th colspan=\"3\"><input type=\"submit\" value=\"Register\"/></th></tr></table></form><!-- </div> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
