/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-04-18 13:18:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.dbutil.*;
import com.can.*;

public final class security_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap-responsive.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap-responsive.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap.js\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/e-canvass/bootstrap/bootstrap.min.js\">\r\n");
      out.write("<title>Security......</title>\r\n");
      out.write("<script>\r\n");
      out.write("function show1()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"show1\").style.display=\"block\";\r\n");
      out.write("\tdocument.getElementById(\"show2\").style.display=\"none\";\r\n");
      out.write("\t}\r\n");
      out.write("function show2()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"show1\").style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById(\"show2\").style.display=\"block\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<body  style=\"background-image: url('/e-canvass/images/3.jpg');background-position:center; background-repeat: no-repeat;height:100%;width:100%;background-attachment: fixed;\">\r\n");
      out.write("<h3 style=\"text-align: center;\">Security....</h3>\r\n");
Connection con=null; ResultSet rs,rs1,rs2; PreparedStatement ps,ps1,ps2;
HttpSession hs=request.getSession(false);
hs.setAttribute("type1", "Teacher");

      out.write("\r\n");
      out.write("<a href=\"/e-canvass/jsp/myposts.jsp\" ><span>Back....</span></a>\r\n");

String userid=(String)hs.getAttribute("loginid");
System.out.println("loginid is "+userid);
String q=request.getQueryString();
hs.setAttribute("id", q);
System.out.println("messageid="+q);
String s1="select * from a"+userid+" where messageid=?";
con=CRUDOperation.createConection();
try
{
ps=con.prepareStatement(s1);
ps.setString(1 , q);
rs=ps.executeQuery();
while(rs.next())
{ 
	System.out.println(" reached");

      out.write("\r\n");
      out.write("<div style=\"left:300px;right:300px;width:50%;position:relative;\">\r\n");
      out.print(rs.getString("post"));
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"left:300px;right:300px;width:50%;position:relative;\">\r\n");

System.out.println("at security end the id is="+q);

      out.write("\r\n");
      out.write("<form action=\"/e-canvass/DeleteRec\" method=\"get\">\r\n");
      out.write("<input type=\"submit\" value=\"Delete\"></form>\r\n");
      out.write("<table style=\"width:100%;\">\r\n");
      out.write("<tr><th><a onclick=\"show1()\">Hide From....</a></th><th><a onclick=\"show2()\">Hidden From....</a></th></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
 
}
}
catch(Exception se)
{
	System.out.println(se);
	}
	
      out.write("\r\n");
      out.write("\t<div id=\"show1\" style=\"display:none;\">\r\n");
      out.write("\t<form action=\"/e-canvass/EideUnhide?");
      out.print(q );
      out.write("\" method=\"post\">\r\n");
      out.write("\t<table style=\"width:100%;\">\r\n");
      out.write("\t<tr><th>Select<th>Name</th><th>Branch</th><th>Status</th></tr>\r\n");
      out.write("\t");
String s2="select * from follow where followedto=?";
	String s3="select * from security where messageid=?";
	System.out.println(" reached2");
	int flag=0;
	try
	{
	ps1=con.prepareStatement(s2);
    ps1.setString(1, userid);
    ps2=con.prepareStatement(s3);
    ps2.setString(1, q);
    rs1=ps1.executeQuery();
    rs2=ps2.executeQuery();
    while(rs1.next())
	{System.out.println("inse hide karsakte hai....?"+rs1.getString("followedby"));
	flag=0;
    	System.out.println("outerwhile");
    	while(rs2.next())
    	{
    		System.out.println("innerwhile.....inse hidden hai:"+rs2.getString("hidefrom"));
		if((rs1.getString("followedby")).equals(rs2.getString("hidefrom")))
		{   flag=1;
			System.out.println(rs1.getString("followedby"));
		}}
		if(flag==0)
		{
    	
      out.write("\r\n");
      out.write("    \t<tr><td style=\"text-align: center;\"><input type=\"checkbox\" value=\"");
      out.print(rs1.getString("followedby") );
      out.write("\" name=\"chkbx\" ></td><td style=\"text-align: center;\">");
      out.print(rs1.getString("followedby") );
      out.write("</td><td style=\"text-align: center;\">");
      out.print(rs1.getString("teachbranch") );
      out.write("</td><td>Visible</td></tr>\r\n");
      out.write("    \t");
}
    	rs2.beforeFirst();
	}
    }	
  catch(Exception se)
	{
		System.out.println(se);
		} 
      out.write("\r\n");
      out.write("\t\t<tr><th><input type=\"submit\" value=\"HIDE\"></th><td></td><td></td></tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
//second table show2 for hideen from..... 
      out.write("\r\n");
      out.write("\t<div id=\"show2\" style=\"display:none;\">\r\n");
      out.write("\t<form action=\"/e-canvass/EideUnhide\" method=\"get\">\r\n");
      out.write("\t<table style=\"width:100%;\">\r\n");
      out.write("\t<tr><th >Select<th>Name</th><th>Branch</th><th>Status</th></tr>\r\n");
      out.write("\t");
 
	String ss="select * from security where messageid=?";
	try
	{
		System.out.println("userid="+userid);
	ps2=con.prepareStatement(ss);
    ps2.setString(1, q);
    rs2=ps2.executeQuery();
	while(rs2.next())
		{ 
	
	
      out.write("\r\n");
      out.write("\t<tr><td style=\"text-align: center;\"><input type=\"checkbox\" value=\"");
      out.print(rs2.getString("hidefrom") );
      out.write("\" name=\"chkbx1\" ></td><td style=\"text-align: center;\">");
      out.print(rs2.getString("hidefrom") );
      out.write("</td><td style=\"text-align: center;\">");
      out.print(rs2.getString("hidefrom") );
      out.write("</td><td>Hidden</td></tr>\r\n");
      out.write("\t");
}}
	catch(Exception se)
	{
		System.out.println(se);
		} 
      out.write("\r\n");
      out.write("\t<tr><th><input type=\"submit\" value=\"UNHIDE\"></th><td></td><td></td></tr>\r\n");
      out.write("\t</table></form></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
